import { post, route } from 'remix/routes'

export const routes = route({
	home: '/',
	connectOauth: '/connect/oauth',
	accountIntegrations: '/account/integrations',
	accountIntegrationsApi: '/account/integrations.json',
	accountPackageInvocationTokens: '/account/package-invocation-tokens',
	accountPackageInvocationTokenNew: '/account/package-invocation-tokens/new',
	accountPackageInvocationTokenDetail:
		'/account/package-invocation-tokens/:tokenId',
	accountPackageInvocationTokensApi: '/account/package-invocation-tokens.json',
	accountPackageInvocationTokensApiPost: post(
		'/account/package-invocation-tokens.json',
	),
	accountRemoteConnectors: '/account/remote-connectors',
	accountRemoteConnectorsApi: '/account/remote-connectors.json',
	accountRemoteConnectorsApiPost: post('/account/remote-connectors.json'),
	accountSecrets: '/account/secrets',
	accountSecretNew: '/account/secrets/new',
	accountSecretDetail: '/account/secrets/:secretId',
	accountSecretUserDetail: '/account/secrets/user/:secretName',
	accountSecretAppDetail: '/account/secrets/app/:appId/:secretName',
	accountSecretSessionDetail: '/account/secrets/session/:sessionId/:secretName',
	accountSecretPackageDetail: '/account/secrets/package/:packageId/:secretName',
	accountSecretsApprove: '/account/secrets/approve',
	accountSecretsApi: '/account/secrets.json',
	accountSecretsApiPost: post('/account/secrets.json'),
	accountProfileApi: '/account/profile.json',
	accountProfileApiPost: post('/account/profile.json'),
	accountExport: '/account/export.json',
	admin: '/admin',
	adminUsers: '/admin/users',
	adminUsersApi: '/admin/users.json',
	adminUsersApiPost: post('/admin/users.json'),
	adminRoles: '/admin/roles',
	adminRolesApi: '/admin/roles.json',
	adminInvites: '/admin/invites',
	adminInvitesApi: '/admin/invites.json',
	adminInvitesApiPost: post('/admin/invites.json'),
	adminCommunityReports: '/admin/community-reports',
	adminCommunityReportsApi: '/admin/community-reports.json',
	adminCommunityReportsApiPost: post('/admin/community-reports.json'),
	community: '/community',
	communityApi: '/community.json',
	communityDetail: '/community/:listingId',
	communityDetailApi: '/community/:listingId.json',
	communityDetailOgImage: '/community/:listingId/og.png',
	communityReportApiPost: post('/community/:listingId/report.json'),
	health: '/health',
	login: '/login',
	privacy: '/privacy',
	resetPassword: '/reset-password',
	verifyEmail: '/verify-email',
	signup: '/signup',
	account: '/account',
	accountDelete: post('/account/delete'),
	auth: post('/auth'),
	session: '/session',
	logout: post('/logout'),
	passwordResetRequest: post('/password-reset'),
	passwordResetConfirm: post('/password-reset/confirm'),
})
